### ISSUE TITLE
Encoded data in WAV format

### ISSUE THREAD

**Issue by vinuk4u** [louisyonge/opus_android#1]
Apologize for raising a question as issue (only bcoz of the unavailability of contact a user).
Have you tried the opus encoded data in wav file itself ?

**Comment by louisyonge** [comment]
Well, I would say it's functional, but it's wise to try it yourself. This is the apk link.  [oplayer](http://www.wandoujia.com/apps/top.oply.oplayer). Have fun.

**Comment by vinuk4u** [comment]
Ya this is awesome. Thank you.
I had checked the wav conversion you did, which is decoding the data.
I will try from my side on making the audio in wav format itself with the encoded data.
Will inform right after its been done.

**Comment by louisyonge** [comment]
Glad to hear it. Enjoy!
