### ISSUE TITLE
what's version of opuslib base on?

### ISSUE THREAD

**Issue by wangduanqing5945** [louisyonge/opus_android#3]
I want to know which version of opus lib your source base on?

**Comment by wangduanqing5945** [comment]
How can i upgrade opus source to 1.1.3? I am good at java，but a little about C/C++.

**Comment by louisyonge** [comment]
version: 1.1-beta
Source codes of opus are under jni folder.  Replace with newer version code and do some MACRO modification for compliation. GOOD LUCK!

**Comment by wangduanqing5945** [comment]
too much source code you changed. I think it will some problem if I force replace. compare and change?

**Comment by louisyonge** [comment]
Agreed. 
Codes are modified for two purpose, one is for compilation, the other is for JNI -- Java Navtive Interface, through which java codes call C/C++ codes.

Only Codes changed for the first purpose might need your attention.  
@wangduanqing5945

**Comment by wangduanqing5945** [comment]
when will you upgrade opus source to 1.1.3 or later?

**Comment by louisyonge** [comment]
@wangduanqing5945 Sorry, no such plan yet. 

Would you please push it to the main repository if you will perform such upgrade in the futher?
