### ISSUE TITLE
Seeking to a specific position not possible

### ISSUE THREAD

**Issue by mrgames13** [louisyonge/opus_android#5]
I'm coding a chat app and using that library for voice notes in this app. For better functionality, it wouldn't be bad to have a seeking functionality there. I've found a seeking function, but it is not that, what I need. Is the seeking function in the code and I am still not finding it or is there a method to make a workaround?
Thanks for answering!

**Comment by louisyonge** [comment]
Well, it is painful to review my codes written 2 years ago. Sorry.

There are many in different code level, but actually they all call the same native method eventually. Below is top Java level method. Please note the parameter "scale", 0 means the beginning of a stream and 1.0 means the ending of a stream.
```
float scale = ((float) progress) / mPlaySeekBar.getMax();
OpusService.seekFile(getApplicationContext(), scale);
```

The method below is the lowest Java level seeking function. 
```
public class OpusTool { 
...
/**
     * Seeking in opus file
     *
     * @param position position in file
     * @return non zero if successful
     */
    public native int seekOpusFile(float position);
}
```

The demo shows the seeking in a stream works fine. But if you want a better performance, you might need to read opus source codes in C in the path "opus_android/opuslib/src/main/jni/".   Thus you can delicately manipulate opus streams as you want.

**Comment by mrgames13** [comment]
Ohh! Thanks for answer!
I had thought, that I have to put the position in seconds as parameter with the seek-method. Thank you for your quick help!
kind regards

**Comment by louisyonge** [comment]
You are welcome. Have a nice day!
